# Generated by Django 6.0.2 on 2026-03-03 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=200, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_description',
            field=models.CharField(max_length=200, verbose_name='product_description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='short_description',
            field=models.CharField(max_length=200, verbose_name='short_description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='stock_price'),
        ),
    ]
