# Generated by Django 6.0.2 on 2026-03-03 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_remove_product_stock_price_product_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.IntegerField(verbose_name='stock'),
        ),
    ]
