# Generated by Django 6.0.2 on 2026-03-03 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_product_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0, verbose_name='stock')),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='shop.stock'),
        ),
    ]
